apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: monitorings.monitoring.com
spec:
  group: monitoring.com
  names:
    kind: Monitoring
    listKind: MonitoringList
    plural: monitorings
    singular: monitoring
  scope: Namespaced

  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Schema for cleaningconfig
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
          description: Spec configures monitoring operator
          properties:
            labels:
              type: object
        spec:
          type: object
          description: Spec configures monitoring operator
          properties:
            teamName:
              type: string
            monitoringNamespace:
              type: string
            grafana:
              type: object
              description: Spec configures monitoring operator
              properties:
                installType:
                  type: string
            prometheus:
              type: object
              description: Spec configures monitoring operator
              properties:
                installType:
                  type: string
                exposeRoute:
                  type: boolean

  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
