apiVersion: monitoring.com/v1alpha1
kind: Monitoring
metadata:
  name: team-development-monitoring
spec:
  teamName: team-development
  monitoringNamespace: team-development-monitoring
  grafana:
    installType: operator
    exposeRoute: true
  prometheus:
    installType: operator
    exposeRoute: true
