- name: deploy operator group
  k8s:
    namespace: "{{ _monitoring_com_monitoring_spec.monitoringNamespace }}"
    definition: "{{lookup('template', 'prometheus-operator-group.yaml')}}"
    state: present

- name: deploy csr-cr
  k8s:
    namespace: "{{ _monitoring_com_monitoring_spec.monitoringNamespace }}"
    definition: "{{lookup('template', 'prometheus-csc-cr.yaml')}}"
    state: present

- name: deploy operator subscription
  k8s:
    namespace: "{{ _monitoring_com_monitoring_spec.monitoringNamespace }}"
    definition: "{{lookup('template', 'prometheus-operator-sub.yaml')}}"
    state: present

- name: deploy prometheus rbac
  k8s:
    namespace: "{{ _monitoring_com_monitoring_spec.monitoringNamespace }}"
    definition: "{{lookup('template', 'prometheus-rbac.yaml')}}"
    state: present

- name: deploy prometheus rolebinding
  k8s:
    namespace: "{{ _monitoring_com_monitoring_spec.monitoringNamespace }}"
    definition: "{{lookup('template', 'prometheus-role-binding.yaml')}}"
    state: present

- name: deploy prometheus instance
  k8s:
    namespace: "{{ _monitoring_com_monitoring_spec.monitoringNamespace }}"
    definition: "{{lookup('template', 'prometheus-instance.yaml')}}"
    state: present

- name: expose route prometheus instance
  k8s:
    namespace: "{{ _monitoring_com_monitoring_spec.monitoringNamespace }}"
    definition: "{{lookup('template', 'prometheus-route.yaml')}}"
    state: present
  when: _monitoring_com_monitoring_spec.prometheus.exposeRoute == true

- name: deploy prometheus service monitor
  k8s:
    namespace: "{{ _monitoring_com_monitoring_spec.monitoringNamespace }}"
    definition: "{{lookup('template', 'prometheus-service-monitor.yaml')}}"
    state: present
