kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monitoring-operator
subjects:
- kind: ServiceAccount
  name: monitoring-operator
  namespace: monitoring-operator
roleRef:
  kind: ClusterRole
  name:  monitoring-operator
  apiGroup: rbac.authorization.k8s.io
