---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: monitoring-operator
  template:
    metadata:
      labels:
        name: monitoring-operator
    spec:
      serviceAccountName: monitoring-operator
      containers:
        - name: monitoring-operator
          image: nlaaziz/monitoring-operator:latest
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "monitoring-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 5
            periodSeconds: 3
      volumes:
        - name: runner
          emptyDir: {}
