apiVersion: operators.coreos.com/v1
kind: CatalogSourceConfig
metadata:
  name: prometheus
  namespace: openshift-marketplace
spec:
  targetNamespace: "{{ monitoringNamespace }}"
  packages: prometheus
  source: community-operators
  publisher: Community
