apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: prometheus
  namespace: "{{ monitoringNamespace }}"
spec:
  channel: beta
  name: prometheus
  source: prometheus
  sourceNamespace: "{{ monitoringNamespace }}"
