apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: prometheus
  namespace: "{{ _monitoring_com_monitoring_spec.monitoringNamespace }}"
spec:
  channel: beta
  name: prometheus
  source: prometheus
  sourceNamespace: "{{ _monitoring_com_monitoring_spec.monitoringNamespace }}"
