apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  generation: 15
  labels:
    k8s-app: prometheus
    team: dpt
  name: app-metrics
  namespace: "{{ monitoringNamespace }}"
spec:
  endpoints:
    - interval: 30s
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_service_annotation_prometheus_io_path
          targetLabel: __metrics_path__
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
          replacement: $1
          separator: ;
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      supervision: 'true'
      team: sofa
